web/account/models.py
from datetime import datetime
from flask_login import current_user

from sqlalchemy import Column, Integer, String, Boolean, ForeignKey
from sqlalchemy.orm import relationship

from web.db import Base


class Account(Base):
    __tablename__ = 'account'

    id = Column(Integer, primary_key=True)
    id_user = Column(Integer, ForeignKey('user.id'))
    id_currency = Column(Integer, ForeignKey('currency.id'))
    currency = relationship('Currency')

    name = Column(String)
    description = Column(String)

    creation_time = Column(String)
    modification_time = Column(String)
    is_actual = Column(Boolean)

    def __init__(self, id_user=0, id_currency=0, name='', description=''):
        if id_user:
            self.id_user = id_user
        elif current_user:
            self.id_user = current_user.get_id()
        self.id_currency = id_currency
        self.name = name
        self.description = description
        self.is_actual = 1
        self.creation_time = datetime.now()
        self.modification_time = None

    def add_form_data(self, data):
        self.name = data.name.data
        self.description = data.description.data
        self.id_currency = data.id_currency.data
        if self.id:
            self.modification_time = datetime.now()

    def invert_is_actual(self):
        if self.is_actual:
            self.is_actual = False
        else:
            self.is_actual = True

    def __repr__(self):
        return f'<Account - {self.name} (ID = {self.id})>'

web/account/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, SelectField, HiddenField
from wtforms.validators import DataRequired


class AccountForm(FlaskForm):
    id = HiddenField('id')
    name = StringField('Название счета', validators=[DataRequired()])
    description = StringField('Описание')
    id_currency = SelectField('Валюта счета')
    submit = SubmitField('Отправить')

web/operation/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, SelectField, DecimalField, SelectMultipleField, DateField, HiddenField
from wtforms.validators import DataRequired


class OperationForm(FlaskForm):
    id = HiddenField('id')
    id_cat = SelectField('Категория', validators=[DataRequired()])
    id_account = SelectField('Счет', validators=[DataRequired()], coerce=int)
    tags = SelectMultipleField('Теги', coerce=int)
    name = StringField('Название', validators=[DataRequired()])
    description = StringField('Описание (опционально)')
    value = DecimalField('Сумма', validators=[DataRequired()])
    creation_time = DateField('Дата операции')
    submit = SubmitField('Отправить')


class OperationsFilterForm(FlaskForm):
    date_from = DateField('Дата с')
    date_to = DateField('Дата по')
    filter_id_cat = SelectField('Категория')
    filter_id_account = SelectField('Счет')
    filter = SubmitField('Отфильтровать')

web/tag/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, HiddenField
from wtforms.validators import DataRequired


class TagForm(FlaskForm):
    id = HiddenField('id')
    name = StringField('Название', validators=[DataRequired()])
    description = StringField('Описание')
    submit = SubmitField('Отправить')

web/account/views.py
from flask import render_template, flash, redirect, url_for, request, Blueprint
from flask_login import current_user, login_required

from .forms import AccountForm
from web.db import session
from web.account.models import Account
from web.currency.models import Currency
from web.operation.models import Operation
from web.obj_history.db_history import save_original_state, get_obj_history, get_deleted_objects


blueprint = Blueprint('account', __name__, url_prefix='/account')


@blueprint.route('/', methods=['GET', 'POST'])
@login_required
def account_list():
    id_account = request.values.get('id', default=0, type=int)
    id_user = current_user.get_id()
    action = request.args.get('action', default='', type=str)
    account = get_current_account(id_account, id_user)

    if action == 'delete' and account.id:
        if not check_is_empty_account(account.id):
            flash(f"Unable to delete account, it has operations. Please, empty account first", category='error')
            return redirect(url_for('account.account_list'))
        else:
            delete_account(account)
            return redirect(url_for('account.account_list'))

    if action == 'switch' and account.id:
        change_account_actual(account)
        return redirect(url_for('account.account_list'))

    form = AccountForm(obj=account)
    form.id_currency.choices = [(str(i), n) for i, n in session.query(Currency.id, Currency.name)]

    if form.validate_on_submit():
        save_account(account, form, id_account)
        return redirect(url_for('account.account_list'))

    to_form = {
        "title": "Accounts",
        "id": id_account,
        "form": form,
        "current_acc": account,
        "accounts": get_accounts_list(id_user),
        "account_history": get_obj_history('Account', account.id),
        "deleted_accounts": get_deleted_objects('Account'),
    }
    return render_template("account/list.html", **to_form)


def get_current_account(id_account, id_user):
    account = session.query(Account).filter(Account.id == id_account and Account.id_user == id_user).one_or_none()
    if not account:
        account = Account()
    return account


def check_is_empty_account(id_account):
    if not session.query(Operation).filter(Operation.id_account == id_account).first():
        return True


def delete_account(account):
    save_original_state('Account', account.id, 'delete', account)
    session.delete(account)
    session.commit()
    flash(f"Account was deleted (id='{account.id}', name='{account.name}')")


def save_account(account, form, id_account):
    if account.id:
        save_original_state('Account', account.id, 'update', account)
    account.add_form_data(form)
    session.add(account)
    session.commit()
    if id_account:
        flash(f"Account was updated (id='{account.id}', name='{account.name}')")
    else:
        flash(f"Account was created (id='{account.id}', name='{account.name}')")


def change_account_actual(account):
    save_original_state('Account', account.id, 'invert_is_actual', account)
    account.invert_is_actual()
    session.add(account)
    session.commit()
    flash(f"Account was switched (id='{account.id}', name='{account.name}')")


def get_accounts_list(id_user):
    return session.query(Account).filter(Account.id_user == id_user).order_by('id').all()

web/operation/views.py
from calendar import monthlen
from datetime import date, datetime, timedelta
from flask import render_template, flash, redirect, url_for, request, Blueprint
from flask_login import current_user, login_required
from werkzeug import ImmutableMultiDict

from .forms import OperationForm, OperationsFilterForm
from web.account.models import Account
from web.db import session
from web.obj_history.db_history import save_original_state, get_obj_history, get_deleted_objects
from web.operation.models import Operation
from web.future_operation.models import FutureOperaion  # без импорта не дает сохранить операцию

from .helpers import get_user_accs, get_user_categories, get_user_categories_tree, get_user_tags, get_user_operations, get_tags_objects


blueprint = Blueprint('operation', __name__, url_prefix='/operation')


@blueprint.route('/', methods=['GET', 'POST'])
@login_required
def operations():
    id_operation = request.values.get('id', default=0, type=int)
    id_user = current_user.get_id()
    action = request.args.get('action', default='', type=str)
    operation = get_current_operation(id_operation, id_user)

    if action == 'delete' and operation.id:
        delete_operation(operation)
        return redirect(url_for('operation.operations'))

    if action == 'switch' and operation.id:
        change_operation_actual(operation)
        return redirect(url_for('category.categories_list'))

    form = OperationForm(obj=operation)
    form.id_account.choices = get_user_accs(id_user)
    form.tags.choices = get_user_tags(id_user)
    form.id_cat.choices = get_user_categories_tree(id_user)

    if form.submit.data and form.validate_on_submit():
        save_operation(operation, form, id_operation, id_user)
        return redirect(url_for('operation.operations'))

    date_from, date_to = get_date_range()
    filter_form = get_operation_filter_form(id_user, date_from, date_to)

    to_form = {
        "title": "Operations",
        "id": id_operation,
        "form": form,
        "date_from": date_from,
        "date_to": date_to,
        'total_value': 100,
        "filter_form": filter_form,
        "current_operation": operation,
        "operations": get_user_operations(
            id_user,
            date_from,
            date_to,
            request.values.get('filter_id_account', default=0, type=int),
            request.values.get('filter_id_cat', default=0, type=int),
            ),
        "category_history": get_obj_history('Operation', operation.id),
        "deleted_categories": get_deleted_objects('Operation'),
    }
    return render_template("operation/list.html", **to_form)


def get_operation_filter_form(id_user, date_from, date_to):
    filter_form = OperationsFilterForm()
    full_field_process(
        filter_form.date_from,
        date_from.strftime(filter_form.date_from.format)
        )
    full_field_process(
        filter_form.date_to,
        date_to.strftime(filter_form.date_to.format)
        )
    filter_form.filter_id_account.choices = get_user_accs(id_user, not_selected_choise=True)
    filter_form.filter_id_cat.choices = get_user_categories_tree(id_user)
    return filter_form


def full_field_process(field, val):
    field.process(ImmutableMultiDict([(field.short_name, val)]))


def get_date_range():
    str_date_from = request.values.get('date_from', '', type=str)
    str_date_to = request.values.get('date_to', '', type=str)
    today = date.today()

    if str_date_from:
        try:
            date_from = datetime.strptime(str_date_from, "%Y-%m-%d").date()
        except ValueError:
            date_from = date(today.year, today.month, 1)
    else:
        date_from = date(today.year, today.month, 1)

    if str_date_to:
        try:
            date_to = datetime.strptime(str_date_to, "%Y-%m-%d").date()
        except ValueError:
            date_to = date(today.year, today.month, monthlen(today.year, today.month))
    else:
        date_to = date(today.year, today.month, monthlen(today.year, today.month))

    if date_to < date_from:
        date_from = date_to - timedelta(days=monthlen(today.year, today.month))

    return date_from, date_to


def get_current_operation(id_operation, id_user):
    operation = session.query(Operation).filter(Operation.id == id_operation).one_or_none()
    if not operation:
        operation = Operation()
    else:
        operation_account = session.query(Account).filter(Account.id == operation.id_account).one()
        if operation_account.id_user != int(id_user):
            operation = Operation()
    return operation


def delete_operation(operation):
    save_original_state('Operation', operation.id, 'delete', operation)
    session.delete(operation)
    session.commit()
    flash(f"Operation was deleted (id='{operation.id}', name='{operation.name}')")


def change_operation_actual(operation):
    save_original_state('Operation', operation.id, 'invert_is_actual', operation)
    operation.invert_is_actual()
    session.add(operation)
    session.commit()
    flash(f"Operation was switched (id='{operation.id}', name='{operation.name}')")


def save_operation(operation, form, id_operation, id_user):
    if operation.id:
        save_original_state('Operation', operation.id, 'update', operation)
    tags_objects_list = get_tags_objects(form.tags.data, id_user)
    operation.form_processing(form, tags_objects_list, id_operation)
    if not tags_objects_list:
        operation.tags.clear()  # Если просто передавать пустое значение, теги не удаляются полностью
    session.add(operation)
    session.commit()
    if id_operation:
        flash(f"Operation was updated (id='{operation.id}', name='{operation.name}')")
    else:
        flash(f"Operation was created (id='{operation.id}', name='{operation.name}')")

web/report/views.py
from flask import render_template, Blueprint
from flask_login import current_user, login_required

from web.db import session
from web.tree import Tree
from web.category.models import Category


blueprint = Blueprint('report', __name__, url_prefix='/report')


@blueprint.route('/', methods=['GET', 'POST'])
@login_required
def reports():
    user_id = current_user.get_id()
    categories = session.query(Category).filter(Category.id_user == user_id).order_by('id').all()
    tree = Tree(categories)

    to_form = {
        "categories": tree.return_tree(),
    }
    return render_template("report/main_report.html", **to_form)

web/shared/views.py
from flask import render_template, Blueprint
from flask_login import login_required

blueprint = Blueprint('shared', __name__, url_prefix='/shared')


@blueprint.route('/')
@login_required
def shared_ops():
    return render_template("shared/list.html")

web/tag/views.py
from flask import render_template, flash, redirect, url_for, request, Blueprint
from flask_login import current_user, login_required

from .forms import TagForm
from web.db import session
from web.obj_history.db_history import save_original_state, get_obj_history, get_deleted_objects
from web.tag.models import Tag


blueprint = Blueprint('tag', __name__, url_prefix='/tag')


@blueprint.route('/', methods=['GET', 'POST'])
@login_required
def tag_list():
    id_tag = request.values.get('id', default=0, type=int)
    id_user = current_user.get_id()
    action = request.args.get('action', default='', type=str)
    tag = get_current_tag(id_tag, id_user)

    if action == 'delete' and tag.id:
        delete_tag(tag)
        return redirect(url_for('tag.tag_list'))

    if action == 'switch' and tag.id:
        change_tag_actual(tag)
        return redirect(url_for('tag.tag_list'))

    form = TagForm(obj=tag)
    if form.validate_on_submit():
        save_tag(tag, form, id_tag)
        return redirect(url_for('tag.tag_list'))

    to_form = {
        "title": "Tags",
        "id": id_tag,
        "form": form,
        "current_tag": tag,
        "tags": get_tags_list(id_user),
        "tag_history": get_obj_history('Tag', tag.id),
        "deleted_tags": get_deleted_objects('Tag'),
    }
    return render_template("tag/list.html", **to_form)


def get_current_tag(id_tag, id_user):
    tag = session.query(Tag).filter(Tag.id == id_tag and Tag.id_user == id_user).one_or_none()
    if not tag:
        tag = Tag()
    return tag


def delete_tag(tag):
    save_original_state('Tag', tag.id, 'delete', tag)
    session.delete(tag)
    session.commit()
    flash(f"Tag was deleted (id='{tag.id}', name='{tag.name}')")


def save_tag(tag, form, id_tag):
    if tag.id:
        save_original_state('Tag', tag.id, 'update', tag)
    tag.add_form_data(form)
    session.add(tag)
    session.commit()
    if id_tag:
        flash(f"Tag was updated (id='{tag.id}', name='{tag.name}')")
    else:
        flash(f"Tag was created (id='{tag.id}', name='{tag.name}')")


def change_tag_actual(tag):
    save_original_state('Tag', tag.id, 'invert_is_actual', tag)
    tag.invert_is_actual()
    session.add(tag)
    session.commit()
    flash(f"Tag was switched (id='{tag.id}', name='{tag.name}')")


def get_tags_list(id_user):
    return session.query(Tag).filter(Tag.id_user == id_user).order_by('id').all()

web/user/views.py
from flask import render_template, flash, redirect, url_for, request, Blueprint
from flask_login import current_user, login_user, logout_user, login_required
from werkzeug.urls import url_parse

from .forms import LoginForm
from web.db import session
from web.user.models import User

blueprint = Blueprint('user', __name__)


@blueprint.route('/')
@blueprint.route('/index')
@login_required
def index():
    return render_template("index.html")


@blueprint.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('user.index'))
    form = LoginForm()
    if form.validate_on_submit():
        user = session.query(User).filter_by(telegram=form.telegram.data).first()
        if user is None or not user.check_password(form.password.data):
            flash('Неправильный логин/пароль', category='login_error')
            return redirect(url_for('user.login'))
        login_user(user, remember=form.remember_me.data)
        next_page = request.args.get('next')
        if not next_page or url_parse(next_page).netloc != '':
            next_page = url_for('user.index')
        return redirect(next_page)
    return render_template('user/login.html', title='Вход', form=form)


@blueprint.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('user.index'))


@blueprint.route('/settings')
@login_required
def user_settings():
    return render_template("user/settings.html")

web/templates/account_form.html
<!-- extend from base layout -->
{% extends "accounts.html" %}


{% block accounts_list %}
{% if data %}
    <table>
        <tr>
            <th>ID</th>
            <th>Currency</th>
            <th>Name</th>
            <th>Description</th>
            <th>Actions</th>
        </tr>
    {% for row in data %}
        <tr>
            <td>{{ row.id }}</td>
            <td>{{ row.currency.name }}</td>
            <td>{{ row.name }}</td>
            <td>{{ row.description }}</td>
            <td><a href='/accounts/?action=edit&id={{ row.id }}'>Edit</a>&nbsp;
                <a href='/accounts/?action=delete&id={{ row.id }}'>Delete</a></td>
        </tr>
    {% endfor %}
    </table>
{% endif %}
{% endblock %}


{% block account_form %}
<h1>Add form</h1>
<form action="" method="post">
    {{ form.hidden_tag() }}
    <p>
        ID - {{ id }}
    </p>

    <p>
            {{ form.name.label }} {{ form.name(size=20) }}
    </p>
    

    <p>
        {{ form.description.label }} {{ form.description(size=20) }}
    </p>
    <p>
        {{ form.id_currency.label }} {{ form.id_currency() }}
    </p>
    <p><input type="submit" value="Submit"></p>
    <p><input type="reset" value="Reset"></p>
    <p><a href='/accounts/'>New Account</a></p>
</form>
{% endblock %}

web/templates/accounts.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block title %}Счета{% endblock %}

{% block app_content %}
<h1>Счета</h1>
<div class="col-md-4">
    {{ wtf.quick_form(form, extra_classes="monospace") }}
</div>
<div class="col-md-8">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>ID</th>
                <th>Валюта</th>
                <th>Название</th>
                <th>Описание</th>
                <th>Действия</th>
                </tr>
        </thead>
        <tbody>
            {% if accounts is iterable %}
                {% for account in accounts %}
                    <tr>
                        <th>{{ account.id }}</th>
                        <td>{{ account.currency.name }}</td>
                        <td>{{ account.name }}</td>
                        <td>{{ account.description }}</td>
                        <td>
                            <a href="?id={{ account.id }}"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a>
                            
                            <a onclick="return confirm('Удалить?')" href="?action=delete&id={{ account.id }}"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></a>
                        </td>
                    </tr>
                {% endfor %}
            {% else %}
                <tr>
                    <td colspan="7">У вас нет счетов</td>
                </tr>
            {% endif %}
        </tbody>
    </table>
</div>
{% endblock %}

web/templates/base.html
{%- extends "bootstrap/base.html" %}

{% block title %} Personal Finance Account System {% endblock %}
{% block styles %}
    {{super()}}
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='style.css')}}">
{% endblock %}


{% block content %}
{% include 'nav.html' %}  
    <div class="container">
            {% with messages = get_flashed_messages() %}
            {% if messages %}
                {% for message in messages %}
                <div class="alert alert-info" role="alert">{{ message }}</div>
                {% endfor %}
            {% endif %}
            {% endwith %}

            {% block app_content %}{% endblock %}
    </div>
{% endblock %}

web/templates/categories.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block title %}Категории{% endblock %}

{% block app_content %}
<h1>Категории</h1>
<div class="col-md-4">
    {{ wtf.quick_form(form, extra_classes="monospace") }}
</div>
<div class="col-md-8">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>ID</th>
                <th>ID родителя</th>
                <th>Название</th>
                <th>Описание</th>
                <th>Действия</th>
                </tr>
        </thead>
        <tbody>
            {% if categories is iterable %}
                {% for category in categories %}
                    <tr>
                        <th>{{ category.id }}</th>
                        <td>{{ category.parent_id }}</td>
                        <td>{{ category.name }}</td>
                        <td>{{ category.description }}</td>
                        <td>
                            <a href="?id={{ category.id }}"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a>
                            
                            <a onclick="return confirm('Удалить?')" href="?action=delete&id={{ category.id }}"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></a>
                        </td>
                    </tr>
                {% endfor %}
            {% else %}
                <tr>
                    <td colspan="7">У вас нет категорий</td>
                </tr>
            {% endif %}
        </tbody>
    </table>
</div>
{% endblock %}

web/templates/index.html
{% extends "base.html" %}
{% block app_content %}

<h1>Главная страница</h1>

{% endblock %}

web/templates/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a href="/" class="navbar-brand">[ PFAS ]</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
        </button>
        {% if current_user.is_authenticated %}
        <ul class="navbar-nav">
            <!-- <li><a href="{{ url_for('shared.shared_ops') }}">Совместные операции</a></li> -->
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('account.account_list') }}">Счета</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('category.categories_list') }}">Категории</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('tag.tag_list') }}">Теги</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('operation.operations') }}">Операции</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('report.reports') }}">Отчеты</a>
            </li>
        </ul>
        {% endif %}
        <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
            <ul class="navbar-nav">
                {% if current_user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a id="navbarDropdownMenuLink" class="nav-link dropdown-toggle" aria-haspopup="false" aria-expanded="false" data-toggle="dropdown" href="#">{{ current_user.name }}</a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href="{{ url_for('user.user_settings') }}">Настройки</a>
                            <a class="dropdown-item" href="{{ url_for('user.logout') }}">Выход</a>
                        </div>
                    </li>
                {% endif %}
                {% if current_user.is_anonymous %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('user.login') }}">Вход</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

web/templates/operations.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block title %}Операции{% endblock %}

{% block app_content %}
<h1>Операции</h1>
<div class="col-md-4">
    {{ wtf.quick_form(form, extra_classes="monospace") }}
</div>
<div class="col-md-8">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>ID</th>
                <th>Счет</th>
                <th>Категория</th>
                <th>Теги</th>
                <th>Название</th>
                <th>Описание</th>
                <th>Сумма</th>
            </tr>
        </thead>
        <tbody>
            {% if operations is iterable %}
                {% for operation in operations %}
                    <tr>
                        <th>{{ operation.id }}</th>
                        <td>{{ operation.id_account }}</td>
                        <td>{{ operation.id_cat }}</td>
                        <td>
                            {%for tag in operation.tags %}
                                {{ tag.name }},
                            {% endfor %}
                        </td>
                        <td>{{ operation.name }}</td>
                        <td>{{ operation.description }}</td>
                        <td>{{ operation.value }}</td>
                        <td>
                            <a href="?action=update&id={{ operation.id }}"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a>
                            
                            <a onclick="return confirm('Удалить?')" href="?action=delete&id={{ operation.id }}"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></a>
                        </td>
                    </tr>
                {% endfor %}
            {% else %}
                <tr>
                    <td colspan="7">У вас нет операций</td>
                </tr>
            {% endif %}
        </tbody>
    </table>
</div>
{% endblock %}

web/templates/shared_accounts.html
{% extends "base.html" %}
{% block title %}Общие счета{% endblock %}
{% block app_content %}
<h1>Общие счета</h1>
{% endblock %}

web/templates/tags.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block title %}Теги{% endblock %}

{% block app_content %}
<h1>Теги</h1>
<div class="col-md-4">
    {{ wtf.quick_form(form, extra_classes="monospace") }}
</div>
<div class="col-md-8">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>ID</th>
                <th>Название</th>
                <th>Описание</th>
                <th>Действия</th>
            </tr>
        </thead>
        <tbody>
            {% if tags is iterable %}
                {% for tag in tags %}
                    <tr>
                        <th>{{ tag.id }}</th>
                        <td>{{ tag.name }}</td>
                        <td>{{ tag.description }}</td>
                        <td>
                            <a href="?id={{ tag.id }}"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a>
                            
                            <a onclick="return confirm('Удалить?')" href="?action=delete&id={{ tag.id }}"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></a>
                        </td>
                    </tr>
                {% endfor %}
            {% else %}
                <tr>
                    <td colspan="7">У вас нет тегов</td>
                </tr>
            {% endif %}
        </tbody>
    </table>
</div>
{% endblock %}